menubar: true
toolbar: 
  - forecolor | bold italic | alignleft aligncenter alignright | fontselect | table | searchreplace |
  - code | link | uploadimage image | media | googlemap |
plugins:
  - link
  - textcolor
  - code
  - table
  - uploadimage
  - media
  - searchreplace
  - imagetools
  - image
  - autoresize
  - googlemap
media_live_embeds: true
autoresize_min_height: 350
paste_merge_formats: true
paste_retain_style_properties: all
body_class: tinymce-editor
language : ja
