menubar: false
toolbar: 
  - forecolor | bold italic | alignleft aligncenter alignright | fontselect | table | searchreplace |
  - code | link | uploadimage | media |
plugins:
  - link
  - textcolor
  - code
  - table
  - uploadimage
  - media
  - searchreplace
paste_merge_formats: true
paste_retain_style_properties: all
body_class: tinymce-editor
language : ja
