menubar: true
toolbar: 
  - forecolor | fontsizeselect | bold italic strikethrough | alignleft aligncenter alignright | fontselect | table | searchreplace |
  - codesample | code | link | uploadimage image | media | fullscreen | preview |
plugins:
  - link
  - textcolor
  - code
  - table
  - uploadimage
  - media
  - searchreplace
  - imagetools
  - image
  - autoresize
  - codesample
  - fullscreen
  - preview
media_live_embeds: true
codesample_languages:
  - text: 'HTML/XML'
    value: 'markup'
  - text: 'JavaScript'
    value: 'javascript'
  - text: 'CSS'
    value: 'css'
  - text: 'PHP'
    value: 'php'
  - text: 'Ruby'
    value: 'ruby'
  - text: 'Python'
    value: 'python'
  - text: 'Java'
    value: 'java'
  - text: 'C'
    value: 'c'
  - text: 'C#'
    value: 'csharp'
  - text: 'C++'
    value: 'cpp'
fontsize_formats: '10px 11px 12px 14px 15px 16px 18px 20px 22px 24px 36px 48px'
autoresize_min_height: 500
paste_merge_formats: true
paste_retain_style_properties: all
body_class: tinymce-editor
language : en
